
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 06 17:42:05 CET 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALSTO = 20;
  public static final int MAP = 36;
  public static final int PLUSPLUS = 25;
  public static final int CHAR = 45;
  public static final int CONST = 26;
  public static final int CONTINUE = 43;
  public static final int GREATER = 37;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int INTERFACE = 14;
  public static final int LESS = 30;
  public static final int MINUS = 22;
  public static final int RPAREN = 7;
  public static final int AND = 27;
  public static final int OR = 44;
  public static final int BOOL = 50;
  public static final int ELESS = 42;
  public static final int COMMA = 11;
  public static final int CLASS = 41;
  public static final int DIV = 21;
  public static final int DOUBLEDOT = 15;
  public static final int DIFFERENT = 38;
  public static final int PLUS = 10;
  public static final int IF = 48;
  public static final int LSQBRACE = 29;
  public static final int DOT = 19;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 24;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 33;
  public static final int NUMBER = 46;
  public static final int EGREATER = 31;
  public static final int MOD = 32;
  public static final int IDENT = 47;
  public static final int BREAK = 34;
  public static final int VOID = 13;
  public static final int UNION = 28;
  public static final int ELSE = 49;
  public static final int LBRACE = 3;
  public static final int READ = 35;
  public static final int WHILE = 39;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 17;
  public static final int PROG = 2;
  public static final int RSQBRACE = 23;
  public static final int DO = 40;
  public static final int PRINT = 12;
  public static final int SET = 16;
}

